### PR TITLE
R interface for MBSGD

### PR DESCRIPTION
**Pull request by yitao-li**
Signed-off-by: Yitao Li <yitao@rstudio.com>

### CODE REVIEW

**Comment by t-kalinowski** [comment]
When I try to build and check this package locally, I get this output:
```
tomasz@horse:~/r-pkgs/cuda.ml
$ MAKEFLAGS=-j11 R CMD check cuda.ml_0.3.1.tar.gz 
* using log directory '/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck'
* using R version 4.1.2 (2021-11-01)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file 'cuda.ml/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'cuda.ml' version '0.3.1'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... NOTE
Found the following apparent object files/libraries:
  inst/libs/libcuml++.so inst/libs/libcuml.so inst/libs/libfaiss.a
  inst/libs/libspdlog.a inst/libs/libtreelite.so
  inst/libs/libtreelite_runtime.so
  inst/libs/libtreelite_runtime_static.a inst/libs/libtreelite_static.a
Object files/libraries should not be included in a source package.
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package 'cuda.ml' can be installed ... OK
* checking installed package size ... NOTE
  installed size is 1160.8Mb
  sub-directories of 1Mb or more:
    libs  1160.5Mb
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... WARNING
Found the following directory with the name of a version control directory:
  ./src/_deps/rapids-cmake-src/.git
These should not be in a package tarball.
Found the following non-empty subdirectories of 'inst' also used by R:
  inst/libs
It is recommended not to interfere with package subdirectories used by
R.
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Documented arguments not in \usage in documentation object 'cuda_ml_sgd':
  ‘normalize_input’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... WARNING
Found the following file(s) containing GNU extensions:
  src/Makefile
  src/_deps/rapids-cmake-build/Makefile
  src/_deps/rapids-cmake-subbuild/Makefile
Portable Makefiles do not use GNU extensions such as +=, :=, $(shell),
$(wildcard), ifeq ... endif, .NOTPARALLEL See section 'Writing portable
packages' in the 'Writing R Extensions' manual.
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking include directives in Makefiles ... OK
* checking compiled code ... NOTE
Note: information on .o files is not available
File ‘/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck/cuda.ml/libs/cuda.ml.so’:
  Found ‘_ZSt4cerr’, possibly from ‘std::cerr’ (C++)
  Found ‘abort’, possibly from ‘abort’ (C)
  Found ‘printf’, possibly from ‘printf’ (C)
  Found ‘stderr’, possibly from ‘stderr’ (C)
File ‘/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck/cuda.ml/libs/libcuml++.so’:
  Found ‘_ZSt4cerr’, possibly from ‘std::cerr’ (C++)
  Found ‘_ZSt4cout’, possibly from ‘std::cout’ (C++)
  Found ‘__printf_chk’, possibly from ‘printf’ (C)
  Found ‘abort’, possibly from ‘abort’ (C)
  Found ‘exit’, possibly from ‘exit’ (C)
  Found ‘putchar’, possibly from ‘putchar’ (C)
  Found ‘puts’, possibly from ‘printf’ (C), ‘puts’ (C)
  Found ‘rand’, possibly from ‘rand’ (C)
  Found ‘stderr’, possibly from ‘stderr’ (C)
  Found ‘stdout’, possibly from ‘stdout’ (C)
File ‘/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck/cuda.ml/libs/libcuml.so’:
  Found ‘__printf_chk’, possibly from ‘printf’ (C)
  Found ‘stderr’, possibly from ‘stderr’ (C)
File ‘/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck/cuda.ml/libs/libtreelite.so’:
  Found ‘_ZSt4cerr’, possibly from ‘std::cerr’ (C++)
File ‘/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck/cuda.ml/libs/libtreelite_runtime.so’:
  Found ‘_ZSt4cerr’, possibly from ‘std::cerr’ (C++)

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs. The detected symbols are linked into the code but
might come from libraries and not actually be called.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
* checking examples ... ERROR
Running examples in 'cuda.ml-Ex.R' failed
The error most likely occurred in:

> ### Name: cuda_ml_agglomerative_clustering
> ### Title: Perform Single-Linkage Agglomerative Clustering.
> ### Aliases: cuda_ml_agglomerative_clustering
> 
> ### ** Examples
> 
> 
> library(cuda.ml)
> library(MASS)
> library(magrittr)
> library(purrr)

Attaching package: ‘purrr’

The following object is masked from ‘package:magrittr’:

    set_names

> 
> set.seed(0L)
> 
> gen_pts <- function() {
+   centers <- list(c(1000, 1000), c(-1000, -1000), c(-1000, 1000))
+   pts <- centers %>%
+     map(~ mvrnorm(50, mu = .x, Sigma = diag(2)))
+ 
+   rlang::exec(rbind, !!!pts) %>% as.matrix()
+ }
> 
> clust <- cuda_ml_agglomerative_clustering(
+   x = gen_pts(),
+   metric = "euclidean",
+   n_clusters = 3L
+ )
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  Collecting joblib>=0.11
    Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
  Building wheels for collected packages: sklearn
    Building wheel for sklearn (setup.py): started
    Building wheel for sklearn (setup.py): finished with status 'done'
    Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1309 sha256=b379a83d9cb17bddcaeb6b1a88703b8056695a4cb3db0573afb1a99a9bd1fdad
    Stored in directory: /home/tomasz/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
  Successfully built sklearn
  Installing collected packages: threadpoolctl, joblib, scikit-learn, sklearn
  Successfully installed joblib-1.1.0 scikit-learn-1.0.1 sklearn-0.0 threadpoolctl-3.0.0
  agglomerative: 
  Agglomerative Clustering: Start test: cuda_ml_agglomerative_clustering() works as expected
  terminate called after throwing an instance of 'std::bad_alloc'
    what():  std::bad_alloc
  Aborted (core dumped)
* checking PDF version of manual ... OK
* DONE

Status: 2 ERRORs, 3 WARNINGs, 3 NOTEs
See
  '/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck/00check.log'
for details.

```
Can you please fix and I can try again?

**Comment by yitao-li** [comment]
@t-kalinowski The bad_alloc error looks like something that would be fixed by rebasing. I rebased this PR just now.

**Comment by yitao-li** [comment]
OK. At least some CIs are passing so that's a good sign. Still awating status of others though.

**Comment by t-kalinowski** [comment]
Fresh everything and a git hard reset gets rid of the malloc error :tada: . There are still some warning and notes though:

```
$ R CMD check cuda.ml_0.3.1.tar.gz 
* using log directory '/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck'
* using R version 4.1.2 (2021-11-01)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file 'cuda.ml/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'cuda.ml' version '0.3.1'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package 'cuda.ml' can be installed ... OK
* checking installed package size ... NOTE
  installed size is  8.3Mb
  sub-directories of 1Mb or more:
    libs   8.0Mb
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... WARNING
Found the following directory with the name of a version control directory:
  ./src/_deps/rapids-cmake-src/.git
These should not be in a package tarball.
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Documented arguments not in \usage in documentation object 'cuda_ml_sgd':
  ‘normalize_input’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... WARNING
Found the following file(s) containing GNU extensions:
  src/Makefile
  src/_deps/rapids-cmake-build/Makefile
  src/_deps/rapids-cmake-subbuild/Makefile
Portable Makefiles do not use GNU extensions such as +=, :=, $(shell),
$(wildcard), ifeq ... endif, .NOTPARALLEL See section 'Writing portable
packages' in the 'Writing R Extensions' manual.
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking include directives in Makefiles ... OK
* checking compiled code ... NOTE
Note: information on .o files is not available
File ‘/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck/cuda.ml/libs/cuda.ml.so’:
  Found ‘_ZSt4cerr’, possibly from ‘std::cerr’ (C++)
  Found ‘abort’, possibly from ‘abort’ (C)
  Found ‘printf’, possibly from ‘printf’ (C)
  Found ‘stderr’, possibly from ‘stderr’ (C)

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs. The detected symbols are linked into the code but
might come from libraries and not actually be called.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking PDF version of manual ... OK
* DONE

Status: 3 WARNINGs, 2 NOTEs
See
  '/home/tomasz/r-pkgs/cuda.ml/cuda.ml.Rcheck/00check.log'
for details.
```

**Comment by yitao-li** [comment]
Alright the warning about non-existent 'normalize_input' param is fixed now.

I don't think there is any point worrying about other warnings about non-portability, etc, because `libcuml++` is explicitly Linux-specific, and the non-portability warnings appear to all have originated from `libcuml++` and also its dependencies such as Treelite which appear to only work with Linux + GNU Make.

**Review by t-kalinowski — APPROVED** [review]

**Pull request merged**
